{% set name = "langchain-aws" %}
{% set version = "0.2.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_aws-{{ version }}.tar.gz
  sha256: 37631f1f4a372a6a313a3d12faeb828dedb331b18dd331294b0db8f23afc71b8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python {{ python_min }},<4.0
    - langchain-core >=0.3.43,<0.4.0
    - boto3 >=1.37.0
    - numpy >=1.0.0,<2.0.0
    - pydantic >=2.10.0,<3

test:
  imports:
    - langchain_aws
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain-aws
  summary: An integration package connecting AWS and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - 3coins
    - dlqqq
    - efriis
    - michaelnchin
