{% set name = "langchain-aws" %}
{% set version = "0.2.29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_aws-{{ version }}.tar.gz
  sha256: a7b24b9b3d96af0ff5c7e55988c178c17e090aa954325b77d725f334eb2c4479

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0
    - langchain-core >=0.3.70,<0.4.0
    - boto3 >=1.39.7
    - numpy >=1.0.0,<2.0.0
    - pydantic >=2.10.0,<3

test:
  imports:
    - langchain_aws
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain-aws
  summary: An integration package connecting AWS and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - 3coins
    - dlqqq
    - efriis
    - michaelnchin
