{% set name = "langchain-aws" %}
{% set version = "0.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_aws-{{ version }}.tar.gz
  sha256: bcc1d4c62addf4ee6cca4e441c63269003e1485069193991e27cae5579bc0353

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.9,<4.0
    - langchain-core >=0.3.15,<0.4.0
    - boto3 >=1.34.131
    - numpy >=1.0.0,<3.0.0
    - pydantic >=2,<3

test:
  imports:
    - langchain_aws
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/langchain-ai/langchain-aws
  summary: An integration package connecting AWS and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - 3coins
    - dlqqq
    - efriis
