{% set name = "langchain-aws" %}
{% set version = "1.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/langchain_aws-{{ version }}.tar.gz
  sha256: 2493abe9a3c9d4b36c0d6d056e5817ab730a77932082fe33d45e2ff2588be581

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0
    - langchain-core >=1.4.7
    - boto3 >=1.43.64
    - numpy >=1.0.0,<3.0.0
    - pydantic >=2.10.6,<3

test:
  imports:
    - langchain_aws
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain-aws
  summary: An integration package connecting AWS and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - 3coins
    - dlqqq
    - efriis
    - michaelnchin
