{% set name = "langchain-aws" %}
{% set version = "0.2.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_aws-{{ version }}.tar.gz
  sha256: 2dc41928ff35f0e37cf521e976f6e87f8263b0a27cfb5007394241f56d1d6644

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python {{ python_min }},<4.0
    - langchain-core >=0.3.27,<0.4.0
    - boto3 >=1.35.74
    - numpy >=1.0.0,<2.0.0
    - pydantic >=2,<3

test:
  imports:
    - langchain_aws
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain-aws
  summary: An integration package connecting AWS and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - 3coins
    - dlqqq
    - efriis
