{% set name = "langchain-aws" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langchain_aws-{{ version }}.tar.gz
  sha256: fc550ca3eb17fd6c4e5605a97b2dfedcfa415abaa39b28bcc273d57c9316d7ec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.9,<4.0
    - langchain-core >=0.3.2,<0.4.0
    - boto3 >=1.34.131
    - numpy >=1.0.0,<2.0.0
    - pydantic >=2,<3

test:
  imports:
    - langchain_aws
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/langchain-ai/langchain-aws
  summary: An integration package connecting AWS and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - 3coins
    - dlqqq
    - efriis
